services:
  - type: web
    name: stayease-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_CALLBACK_URL
        sync: false
      - key: FACEBOOK_GRAPH_VERSION
        value: v26.0
      - key: RESEND_API_KEY
        sync: false
      - key: OTP_FROM_EMAIL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_PHONE
        sync: false

  - type: web
    name: stayease-web
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_ADMIN_API_BASE_URL
        sync: false
