"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useLocale } from "next-intl";
import { ArrowRight, BadgeCheck, CalendarDays, Clock3, Eye, Headphones, MapPin, Search, ShieldCheck, Star, Users } from "lucide-react";

const hotels = [
  ["Novotel Danang Premier Han River", "Da Nang", 4.6, 1248, 1890000, "oceanview-resort-da-nang", "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&auto=format&fit=crop&q=85"],
  ["Conrad Hanoi", "Hanoi", 4.7, 982, 2450000, "hanoi-heritage-hotel", "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&auto=format&fit=crop&q=85"],
  ["Anantara Hoi An Resort", "Hoi An", 4.8, 1102, 2150000, "grand-city-hotel-hcm", "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900&auto=format&fit=crop&q=85"],
  ["Pullman Phu Quoc Beach Resort", "Phu Quoc", 4.5, 873, "1720000", "sunset-paradise-resort-phu-quoc", "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=900&auto=format&fit=crop&q=85"],
] as const;

const articles = [
  ["guide", "https://images.unsplash.com/photo-1540872927746-3afded7f70c5?w=1000&auto=format&fit=crop&q=85"],
  ["tips", "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1000&auto=format&fit=crop&q=85"],
  ["food", "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=1000&auto=format&fit=crop&q=85"],
] as const;

const copy = {
  vi:{title:"Tìm kỳ nghỉ hoàn hảo",sub:"Khách sạn tiện nghi, giá tốt và trải nghiệm khó quên.",where:"Bạn muốn đi đâu?",whereHint:"Thành phố, khách sạn hoặc điểm đến",checkIn:"Nhận phòng",checkOut:"Trả phòng",guests:"Số khách",guestValue:"2 người lớn · 0 trẻ em",search:"Tìm khách sạn",best:"Đảm bảo giá tốt nhất",cancel:"Hủy miễn phí",support:"Hỗ trợ khách hàng 24/7",recent:"Đã xem gần đây",allRecent:"Xem tất cả",reviews:"đánh giá",night:"/ đêm",viewed:"Đã xem",travel:"Mẹo hay & cảm hứng du lịch",allArticles:"Xem tất cả bài viết",read:"Đọc thêm",tags:{guide:"Cẩm nang điểm đến",tips:"Mẹo du lịch",food:"Ẩm thực & văn hóa"},titles:{guide:"5 điểm đến ẩn mình đáng khám phá tại Việt Nam",tips:"Cách chuẩn bị hành lý thông minh cho mọi chuyến đi",food:"Cẩm nang ẩm thực Việt Nam dành cho tín đồ ăn uống"},descs:{guide:"Khám phá những điểm đến ít người biết với cảnh đẹp, văn hóa phong phú và trải nghiệm khó quên.",tips:"Các mẹo thiết yếu giúp bạn mang hành lý gọn nhẹ và tận hưởng trọn vẹn chuyến đi.",food:"Khám phá hương vị làm nên nét độc đáo của ẩm thực Việt, từ đường phố đến đặc sản vùng miền."}},
  en:{title:"Find your perfect stay",sub:"Comfortable hotels, great prices, unforgettable experiences.",where:"Where to?",whereHint:"City, hotel, or destination",checkIn:"Check in",checkOut:"Check out",guests:"Guests",guestValue:"2 adults · 0 children",search:"Search hotels",best:"Best Price Guarantee",cancel:"Free Cancellation",support:"24/7 Customer Support",recent:"Recently Viewed",allRecent:"View all recently viewed",reviews:"reviews",night:"/ night",viewed:"Viewed",travel:"Travel Tips & Inspiration",allArticles:"View all articles",read:"Read more",tags:{guide:"Destination Guide",tips:"Travel Tips",food:"Food & Culture"},titles:{guide:"5 Must-Visit Hidden Gems in Vietnam",tips:"How to Pack Smart for Any Trip",food:"A Food Lover's Guide to Vietnam"},descs:{guide:"Explore lesser-known destinations that offer breathtaking views, rich culture, and unforgettable experiences.",tips:"Essential packing tips and tricks to help you travel light, stay prepared, and make the most of every journey.",food:"From street eats to regional specialties, discover the flavors that make Vietnamese cuisine unforgettable."}},
  ko:{title:"완벽한 숙소를 찾아보세요",sub:"편안한 호텔, 합리적인 가격, 잊지 못할 경험.",where:"어디로 가시나요?",whereHint:"도시, 호텔 또는 여행지",checkIn:"체크인",checkOut:"체크아웃",guests:"투숙객",guestValue:"성인 2명 · 어린이 0명",search:"호텔 검색",best:"최저가 보장",cancel:"무료 취소",support:"24시간 고객 지원",recent:"최근 본 숙소",allRecent:"최근 본 숙소 모두 보기",reviews:"후기",night:"/ 1박",viewed:"조회함",travel:"여행 팁 & 영감",allArticles:"모든 글 보기",read:"더 읽기",tags:{guide:"여행지 가이드",tips:"여행 팁",food:"음식 & 문화"},titles:{guide:"베트남에서 꼭 가봐야 할 숨은 명소 5곳",tips:"모든 여행을 위한 스마트한 짐 싸기",food:"미식가를 위한 베트남 음식 가이드"},descs:{guide:"아름다운 풍경과 풍부한 문화, 특별한 경험을 선사하는 숨은 여행지를 만나보세요.",tips:"가볍고 알차게 여행하도록 도와주는 필수 짐 싸기 팁을 확인하세요.",food:"길거리 음식부터 지역 특선까지 베트남 요리의 매력적인 맛을 발견하세요."}},
} as const;

export default function HomeTopContent(){
  const locale=useLocale() as keyof typeof copy; const t=copy[locale]||copy.en; const router=useRouter();
  const [destination,setDestination]=useState(""); const [checkIn,setCheckIn]=useState(""); const [checkOut,setCheckOut]=useState("");
  const money=(value:number|string)=>new Intl.NumberFormat(locale==="vi"?"vi-VN":locale==="ko"?"ko-KR":"en-US").format(Number(value));
  const search=(e:FormEvent)=>{e.preventDefault();const p=new URLSearchParams();if(destination)p.set("search",destination);if(checkIn)p.set("checkIn",checkIn);if(checkOut)p.set("checkOut",checkOut);router.push(`/${locale}/hotels?${p}`)};
  return <>
    <section className="relative isolate overflow-hidden border-b border-slate-200 bg-slate-100 py-5 dark:border-slate-800 dark:bg-slate-950 sm:py-7"><Image src="/images/hero-bg.jpg" alt="StayEase" fill priority className="-z-20 object-cover opacity-30 dark:opacity-20" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-white/90 via-white/70 to-white/85 dark:from-slate-950/95 dark:via-slate-950/70 dark:to-slate-950/90"/><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="text-center"><h1 className="text-3xl font-black tracking-tight text-[#0b1f44] dark:text-white sm:text-4xl">{t.title}</h1><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{t.sub}</p></div><form onSubmit={search} className="mt-4 grid gap-2 rounded-2xl border border-white/70 bg-white/95 p-3 shadow-xl backdrop-blur dark:border-slate-700 dark:bg-slate-900/95 md:grid-cols-[1.25fr_1fr_1fr_1fr_auto]">
      <label className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 dark:border-slate-700"><MapPin className="h-5 w-5 text-blue-600"/><span className="min-w-0 flex-1"><small className="block text-[10px] text-slate-500">{t.where}</small><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder={t.whereHint} className="w-full bg-transparent text-xs font-semibold outline-none placeholder:font-normal"/></span></label>
      <label className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 dark:border-slate-700"><CalendarDays className="h-5 w-5"/><span className="min-w-0 flex-1"><small className="block text-[10px] text-slate-500">{t.checkIn}</small><input type="date" value={checkIn} onChange={e=>setCheckIn(e.target.value)} className="w-full bg-transparent text-xs font-semibold outline-none"/></span></label>
      <label className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 dark:border-slate-700"><CalendarDays className="h-5 w-5"/><span className="min-w-0 flex-1"><small className="block text-[10px] text-slate-500">{t.checkOut}</small><input type="date" value={checkOut} onChange={e=>setCheckOut(e.target.value)} className="w-full bg-transparent text-xs font-semibold outline-none"/></span></label>
      <div className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 dark:border-slate-700"><Users className="h-5 w-5"/><span><small className="block text-[10px] text-slate-500">{t.guests}</small><strong className="text-xs">{t.guestValue}</strong></span></div><button className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3 text-xs font-bold text-white hover:bg-blue-700"><Search className="h-4 w-4"/>{t.search}</button>
    </form><div className="mt-3 flex flex-wrap justify-center gap-x-8 gap-y-2 text-[11px] font-semibold text-slate-700 dark:text-slate-300">{[[BadgeCheck,t.best],[Clock3,t.cancel],[Headphones,t.support]].map(([Icon,label]:any)=><span key={label} className="flex items-center gap-2"><Icon className="h-4 w-4 text-blue-600"/>{label}</span>)}</div></div></section>
    <div className="mx-auto max-w-7xl space-y-5 px-4 py-5 sm:px-6 lg:px-8"><section><div className="mb-3 flex items-end justify-between"><h2 className="text-xl font-black sm:text-2xl">{t.recent}</h2><Link href={`/${locale}/hotels`} className="hidden items-center gap-1 text-xs font-bold text-blue-600 sm:flex">{t.allRecent}<ArrowRight className="h-3.5 w-3.5"/></Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{hotels.map(([name,city,rating,count,price,slug,image])=><Link href={`/${locale}/hotels/${slug}`} key={name} className="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg dark:border-slate-800 dark:bg-slate-900"><div className="relative h-36 overflow-hidden"><Image src={image} alt={name} fill sizes="330px" className="object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-3"><h3 className="truncate text-sm font-extrabold">{name}</h3><div className="mt-1 flex items-center justify-between text-[10px] text-slate-500"><span><MapPin className="mr-1 inline h-3 w-3"/>{city}, Vietnam</span><strong className="text-blue-600">★ {rating}</strong></div><p className="mt-2 text-[10px] text-slate-500">({money(count)} {t.reviews})</p><div className="mt-1 flex items-end justify-between"><strong className="text-sm">{money(price)} VND</strong><span className="text-[10px] text-slate-500">{t.night}</span></div><span className="mt-2 inline-flex items-center gap-1 rounded-md bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-600 dark:bg-blue-950"><Eye className="h-3 w-3"/>{t.viewed}</span></div></Link>)}</div></section>
    <section><div className="mb-3 flex items-end justify-between"><h2 className="text-xl font-black sm:text-2xl">{t.travel}</h2><Link href={`/${locale}/destinations`} className="hidden items-center gap-1 text-xs font-bold text-blue-600 sm:flex">{t.allArticles}<ArrowRight className="h-3.5 w-3.5"/></Link></div><div className="grid gap-3 md:grid-cols-3">{articles.map(([id,image],index)=><Link href={`/${locale}/destinations`} key={id} className="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:shadow-lg dark:border-slate-800 dark:bg-slate-900"><div className="relative h-36 overflow-hidden"><Image src={image} alt={t.titles[id]} fill sizes="450px" className="object-cover transition duration-500 group-hover:scale-105"/><span className={`absolute left-2 top-2 rounded-full px-3 py-1 text-[10px] font-bold text-white ${index===0?"bg-blue-600":index===1?"bg-cyan-600":"bg-purple-600"}`}>{t.tags[id]}</span></div><div className="p-3"><h3 className="text-sm font-extrabold">{t.titles[id]}</h3><p className="mt-1 line-clamp-2 text-[11px] leading-relaxed text-slate-500">{t.descs[id]}</p><span className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-blue-600">{t.read}<ArrowRight className="h-3.5 w-3.5"/></span></div></Link>)}</div></section></div>
  </>;
}
